t ?= esp8266

ifeq ($t, esp8266)
BOARD := d1_mini
BAUD := 921600
TERMINAL_SPEED := 115200
TERMINAL_EXTRA_FLAGS := -C serialout.txt
XTAL := 80
F_CPU := 80
EESZ := 4M
CPPFLAGS = -DUSER_SETUP_LOADED -DILI9341_DRIVER -DTFT_CS=PIN_D8 -DTFT_DC=PIN_D1 \
	-DTFT_RST=-1 -DSPI_FREQUENCY=40000000 -DLOAD_GLCD \
	-DHARDWARE_H=\"hw/esp8bit.h\" -DNO_STORAGE
CPPFLAGS += -DDEBUGGING -DCPU_DEBUG=false -Wall
LIBRARIES = TFT_eSPI SpiRAM
endif

ifeq ($t, esp32)
UPLOADSPEED := 921600
SPIFFS_IMAGE :=
LIBRARIES = FS SPIFFS

ifeq ($b, lilygo)
BOARD := ttgo-t7-v14-mini32
TERMINAL_SPEED := 115200
SERIAL_PORT := /dev/ttyACM0
CPPFLAGS := -DHARDWARE_H=\"hw/ttgo-t7-v14-mini32.h\"
LIBRARIES += FabGL WiFi

else
BOARD := node32s
CPPFLAGS := -DUSER_SETUP_LOADED -DILI9341_DRIVER -DTFT_CS=5 -DTFT_DC=2 \
	-DTFT_RST=-1 -DTFT_WIDTH=240 -DTFT_HEIGHT=320 \
	-DSPI_FREQUENCY=40000000 -DLOAD_GLCD \
	-DHARDWARE_H=\"hw/node32s-example.h\"
LIBRARIES += TFT_eSPI
endif
endif

include $t.mk
