t ?= esp8266

TERMINAL_SPEED := 115200
#CPPFLAGS = -Wall -DNO_STORAGE -DNO_SPIRAM -DUSE_OWN_KBD -DPS2_SERIAL_KBD=\"UK\" -DSIMPLE_TIMER_MICROS
CPPFLAGS = -Wall -DNO_STORAGE -DNO_SPIRAM -DUSE_OWN_KBD -DHW_SERIAL_KBD -DSIMPLE_TIMER_MICROS
LIBRARIES = SPI PS2KeyAdvanced PS2KeyMap SimpleTimer

ifeq ($t, esp8266)
BOARD := d1_mini
baud := 921600
xtal := 80
eesz := 4M
CPPFLAGS += -DUSER_SETUP_LOADED -DILI9341_DRIVER -DTFT_CS=PIN_D8 -DTFT_DC=PIN_D1 \
	-DTFT_RST=-1 -DSPI_FREQUENCY=40000000 -DLOAD_GLCD -DHARDWARE_H=\"hw/esp8bit.h\"
LIBRARIES += TFT_eSPI
endif

ifeq ($t, esp32)
ifeq ($b, lilygo)
BOARD := ttgo-t7-v14-mini32
SERIAL_PORT := /dev/ttyACM0
LIBRARIES += ESP32Lib

else
BOARD := node32s
CPPFLAGS += -DUSE_OWN_DISPLAY -DSS_DISPLAY -DPB_KEYPAD -DHARDWARE_H=\"hw/esp32-example.h\"
endif
endif

include $t.mk
