t ?= esp8266

ifeq ($t, esp8266)
BOARD := d1_mini
BAUD := 921600
TERMINAL_SPEED := 115200
TERMINAL_EXTRA_FLAGS := -C serialout.txt
XTAL := 80
F_CPU := 80
EESZ := 4M
CPPFLAGS = -DUSER_SETUP_LOADED -DILI9341_DRIVER -DTFT_CS=PIN_D8 -DTFT_DC=PIN_D1 \
	-DTFT_RST=-1 -DSPI_FREQUENCY=40000000 -DLOAD_GLCD \
	-DHARDWARE_H=\"hw/esp8bit.h\"
CPPFLAGS += -DDEBUGGING -DCPU_DEBUG=false -Wall
LIBRARIES = TFT_eSPI SpiRAM LittleFS
endif

include $t.mk
